[Addon]
Name[ja]=Android キーボード
Name[ko]=안드로이드 키보드
Name[ru]=Клавиатура Android
Name[zh_CN]=Android 英文键盘
Name[zh_TW]=Android 鍵盤
Name=Android Keyboard
Type=SharedLibrary
Library=libandroidkeyboard
Category=InputMethod
Version=0.1.2
Configurable=True

[Addon/OptionalDependencies]
0=spell
1=quickphrase
