[Addon]
Name[ja]=Android フロントエンド
Name[ko]=안드로이드 프론트엔드
Name[ru]=Интерфейс Android
Name[zh_CN]=Android 输入法前端
Name[zh_TW]=Android 前端
Name=Android Frontend
Type=SharedLibrary
Library=libandroidfrontend
Category=Frontend
Version=0.1.2
