[Addon]
Name[ja]=Android トーストと通知
Name[ru]=Всплывающие подсказки и уведомления Android
Name[zh_CN]=Android 弹出提示与通知
Name[zh_TW]=Android 浮動式訊息與通知
Name=Android Toast & Notification
Type=SharedLibrary
Library=libandroidnotification
Category=Module
Version=0.1.2
OnDemand=True
Configurable=True

[Addon/Dependencies]
0=androidfrontend:0.1.2
