[Addon]
Name[ca]=Puntuació
Name[da]=Tegnsætning
Name[de]=Interpunktion
Name[ja]=句読点
Name[ko]=문장부호
Name[ru]=Пунктуация
Name[zh_CN]=标点
Name[zh_TW]=標點
Name=Punctuation
Category=Module
Version=5.1.9
Library=libpunctuation
Type=SharedLibrary
OnDemand=True
Configurable=True

[Addon/Dependencies]
0=core:5.1.13

[Addon/OptionalDependencies]
0=notifications
